### ISSUE TITLE
Failing to build

### ISSUE THREAD

**Issue by evergreenbear** [PixelPlusUI/manifest#1]
Hello,
Building gives this error.
`FAILED: //frameworks/base/services/core:services.core.unboosted javac [common]
Outputs: out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/services.core.unboosted.jar
Error: exited with code: 1
Command: rm -rf "out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/classes" "out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/anno" "out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/srcjars" && mkdir -p "out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/classes" "out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/anno" "out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/srcjars" && out/soong/host/linux-x86/bin/zipsync -d out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/srcjars -l out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/srcjars/list -f "*.java" out/soong/.intermediates/frameworks/base/services/core/services.core.protologsrc/gen/services.core.protolog.srcjar out/soong/.intermediates/frameworks/base/services/core/xsd/platform-compat-config/gen/java/com_android_server_compat_config_xsdcgen.srcjar out/soong/.intermediates/frameworks/base/services/core/xsd/display-device-config/gen/java/com_android_server_display_config_xsdcgen.srcjar out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/gen/aidl/aidl0.srcjar && (if [ -s out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/srcjars/list ] || [ -s out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/services.core.unboosted.jar.rsp ] ; then out/soong/host/linux-x86/bin/soong_javac_wrapper prebuilts/jdk/jdk11/linux-x86/bin/javac -J-Xmx2048M -J-XX:OnError="cat hs_err_pid%p.log" -J-XX:CICompilerCount=6 -J-XX:+UseDynamicNumberOfGCThreads -Xmaxerrs 9999999 -encoding UTF-8 -sourcepath "" -g -XDskipDuplicateBridges=true -XDstringConcat=inline -processorpath out/soong/.intermediates/tools/platform-compat/java/android/processor/compat/changeid/compat-changeid-annotation-processor/linux_glibc_common/withres/compat-changeid-annotation-processor.jar -processor android.processor.compat.changeid.ChangeIdProcessor -g:source,lines -Xlint:-dep-ann --system=out/soong/.intermediates/libcore/mmodules/core_platform_api/core-platform-api-stubs-system-modules/android_common/system -classpath out/soong/.intermediates/frameworks/base/ext/android_common/turbine-combined/ext.jar:out/soong/.intermediates/frameworks/base/framework/android_common/turbine-combined/framework.jar:out/soong/.intermediates/frameworks/base/services/net/services.net/android_common/turbine-combined/services.net.jar:out/soong/.intermediates/hardware/interfaces/light/2.0/android.hardware.light-V2.0-java/android_common/turbine-combined/android.hardware.light-V2.0-java.jar:out/soong/.intermediates/hardware/interfaces/power/aidl/android.hardware.power-java/android_common/turbine-combined/android.hardware.power-java.jar:out/soong/.intermediates/hardware/interfaces/power/1.0/android.hardware.power-V1.0-java/android_common/turbine-combined/android.hardware.power-V1.0-java.jar:out/soong/.intermediates/hardware/interfaces/vibrator/aidl/android.hardware.vibrator-java/android_common/turbine-combined/android.hardware.vibrator-java.jar:out/soong/.intermediates/packages/modules/IPsec/android.net.ipsec.ike.stubs.module_lib/android_common/turbine-combined/android.net.ipsec.ike.stubs.module_lib.jar:out/soong/.intermediates/tools/platform-compat/java/android/compat/annotation/app-compat-annotations/android_common/turbine-combined/app-compat-annotations.jar:out/soong/.intermediates/frameworks/base/packages/Tethering/common/TetheringLib/framework-tethering.stubs.module_lib/android_common/turbine-combined/framework-tethering.stubs.module_lib.jar:out/soong/.intermediates/frameworks/base/apex/permission/service/service-permission.stubs.system_server/android_common/turbine-combined/service-permission.stubs.system_server.jar:out/soong/.intermediates/system/timezone/distro/core/time_zone_distro/android_common/turbine-combined/time_zone_distro.jar:out/soong/.intermediates/system/timezone/distro/installer/time_zone_distro_installer/android_common/turbine-combined/time_zone_distro_installer.jar:out/soong/.intermediates/hardware/interfaces/authsecret/1.0/android.hardware.authsecret-V1.0-java/android_common/turbine-combined/android.hardware.authsecret-V1.0-java.jar:out/soong/.intermediates/hardware/interfaces/broadcastradio/2.0/android.hardware.broadcastradio-V2.0-java/android_common/turbine-combined/android.hardware.broadcastradio-V2.0-java.jar:out/soong/.intermediates/hardware/interfaces/health/1.0/android.hardware.health-V1.0-java/android_common/turbine-combined/android.hardware.health-V1.0-java.jar:out/soong/.intermediates/hardware/interfaces/health/2.0/android.hardware.health-V2.0-java/android_common/turbine-combined/android.hardware.health-V2.0-java.jar:out/soong/.intermediates/hardware/interfaces/health/2.1/android.hardware.health-V2.1-java/android_common/turbine-combined/android.hardware.health-V2.1-java.jar:out/soong/.intermediates/hardware/interfaces/light/aidl/android.hardware.light-java/android_common/turbine-combined/android.hardware.light-java.jar:out/soong/.intermediates/hardware/interfaces/tv/cec/1.0/android.hardware.tv.cec-V1.0-java/android_common/turbine-combined/android.hardware.tv.cec-V1.0-java.jar:out/soong/.intermediates/hardware/interfaces/weaver/1.0/android.hardware.weaver-V1.0-java/android_common/turbine-combined/android.hardware.weaver-V1.0-java.jar:out/soong/.intermediates/hardware/interfaces/biometrics/face/1.0/android.hardware.biometrics.face-V1.0-java/android_common/turbine-combined/android.hardware.biometrics.face-V1.0-java.jar:out/soong/.intermediates/hardware/interfaces/biometrics/fingerprint/2.2/android.hardware.biometrics.fingerprint-V2.2-java/android_common/turbine-combined/android.hardware.biometrics.fingerprint-V2.2-java.jar:out/soong/.intermediates/hardware/interfaces/oemlock/1.0/android.hardware.oemlock-V1.0-java/android_common/turbine-combined/android.hardware.oemlock-V1.0-java.jar:out/soong/.intermediates/hardware/interfaces/configstore/1.0/android.hardware.configstore-V1.0-java/android_common/turbine-combined/android.hardware.configstore-V1.0-java.jar:out/soong/.intermediates/hardware/interfaces/contexthub/1.0/android.hardware.contexthub-V1.0-java/android_common/turbine-combined/android.hardware.contexthub-V1.0-java.jar:out/soong/.intermediates/hardware/interfaces/rebootescrow/aidl/android.hardware.rebootescrow-java/android_common/turbine-combined/android.hardware.rebootescrow-java.jar:out/soong/.intermediates/hardware/interfaces/soundtrigger/2.3/android.hardware.soundtrigger-V2.3-java/android_common/turbine-combined/android.hardware.soundtrigger-V2.3-java.jar:out/soong/.intermediates/system/libhidl/transport/manager/1.2/android.hidl.manager-V1.2-java/android_common/turbine-combined/android.hidl.manager-V1.2-java.jar:out/soong/.intermediates/frameworks/av/media/libaudioclient/capture_state_listener-aidl-java/android_common/turbine-combined/capture_state_listener-aidl-java.jar:out/soong/.intermediates/packages/modules/DnsResolver/dnsresolver_aidl_interface-java/android_common/turbine-combined/dnsresolver_aidl_interface-java.jar:out/soong/.intermediates/system/netd/server/netd_aidl_interfaces-platform-java/android_common/turbine-combined/netd_aidl_interfaces-platform-java.jar:out/soong/.intermediates/frameworks/base/cmds/idmap2/overlayable_policy_aidl-java/android_common/turbine-combined/overlayable_policy_aidl-java.jar:out/soong/.intermediates/frameworks/native/services/surfaceflinger/sysprop/SurfaceFlingerProperties/android_common/turbine-combined/SurfaceFlingerProperties.jar:out/soong/.intermediates/hardware/custom/interfaces/biometrics/fingerprint/inscreen/1.0/vendor.lineage.biometrics.fingerprint.inscreen-V1.0-java/android_common/turbine-combined/vendor.lineage.biometrics.fingerprint.inscreen-V1.0-java.jar -source 1.9 -target 1.9 -d out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/classes -s out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/anno @out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/services.core.unboosted.jar.rsp @out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/srcjars/list ; fi ) && out/soong/host/linux-x86/bin/soong_zip -jar -o out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/services.core.unboosted.jar -C out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/classes -D out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/classes && rm -rf "out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/srcjars"
Output:
[1mout/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/srcjars/frameworks/base/services/core/java/com/android/server/display/DisplayModeDirector.java:1612: [31merror:[0m[1m cannot find symbol[0m
        DeviceConfigInterface getDeviceConfig();
[1m        [32m^[0m[1m[0m
  symbol:   class DeviceConfigInterface
  location: interface Injector
[1mout/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/srcjars/frameworks/base/services/core/java/com/android/server/display/DisplayModeDirector.java:1629: [31merror:[0m[1m cannot find symbol[0m
        public DeviceConfigInterface getDeviceConfig() {
[1m               [32m^[0m[1m[0m
  symbol:   class DeviceConfigInterface
  location: class RealInjector
2 errors
`

**Comment by iam-shanmukha** [comment]
Any Update? Same Issue
